/**
 * Prebuilt types emitter.
 *
 * Generates TypeScript type definitions for PrebuiltTypes registry
 * from field selection data and schema.
 *
 * @module
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AnyGraphqlSchema } from "@soda-gql/core";
import { calculateFieldsType, generateInputType } from "@soda-gql/core";
import { err, ok, type Result } from "neverthrow";
import { type BuilderError, builderErrors } from "../errors";
import type { FieldSelectionsMap } from "./extractor";

/**
 * Options for emitting prebuilt types.
 */
export type PrebuiltTypesEmitterOptions = {
  /**
   * Schema definitions per schema name.
   * These come from the codegen output.
   */
  readonly schemas: Record<string, AnyGraphqlSchema>;
  /**
   * Field selections extracted from the builder.
   */
  readonly fieldSelections: FieldSelectionsMap;
  /**
   * Output directory (where prebuilt/types.ts should be written).
   * This should be the same as config.outdir.
   */
  readonly outdir: string;
};

type PrebuiltTypeEntry = {
  readonly key: string;
  readonly inputType: string;
  readonly outputType: string;
};

/**
 * Group field selections by schema.
 * Uses the schema label to group selections.
 */
const groupBySchema = (
  fieldSelections: FieldSelectionsMap,
  schemas: Record<string, AnyGraphqlSchema>,
): Map<string, { fragments: PrebuiltTypeEntry[]; operations: PrebuiltTypeEntry[] }> => {
  const grouped = new Map<string, { fragments: PrebuiltTypeEntry[]; operations: PrebuiltTypeEntry[] }>();

  // Initialize groups for each schema
  for (const schemaName of Object.keys(schemas)) {
    grouped.set(schemaName, { fragments: [], operations: [] });
  }

  // For now, assume single schema named "default"
  // In the future, this could be extended to support multi-schema setups
  const defaultSchemaName = Object.keys(schemas)[0];
  if (!defaultSchemaName) {
    return grouped;
  }

  const schema = schemas[defaultSchemaName];
  if (!schema) {
    return grouped;
  }

  const group = grouped.get(defaultSchemaName);
  if (!group) {
    return grouped;
  }

  for (const [_canonicalId, selection] of fieldSelections) {
    if (selection.type === "fragment") {
      // Skip fragments without keys (they can't be looked up)
      if (!selection.key) {
        continue;
      }

      try {
        const outputType = calculateFieldsType(schema, selection.fields);
        group.fragments.push({
          key: selection.key,
          inputType: "void", // Fragments input is variables, simplified to void for now
          outputType,
        });
      } catch (error) {
        console.warn(
          `[prebuilt] Failed to calculate type for fragment "${selection.key}": ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    } else if (selection.type === "operation") {
      try {
        const outputType = calculateFieldsType(schema, selection.fields);
        const inputType = generateInputType(schema, selection.variableDefinitions);
        group.operations.push({
          key: selection.operationName,
          inputType,
          outputType,
        });
      } catch (error) {
        console.warn(
          `[prebuilt] Failed to calculate type for operation "${selection.operationName}": ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    }
  }

  return grouped;
};

/**
 * Generate the TypeScript code for prebuilt types.
 */
const generateTypesCode = (grouped: Map<string, { fragments: PrebuiltTypeEntry[]; operations: PrebuiltTypeEntry[] }>): string => {
  const lines: string[] = [
    "/**",
    " * Prebuilt type registry.",
    " *",
    " * This file is auto-generated by @soda-gql/builder.",
    " * Do not edit manually.",
    " *",
    " * @module",
    " * @generated",
    " */",
    "",
    'import type { PrebuiltTypeRegistry } from "@soda-gql/core";',
    "",
  ];

  for (const [schemaName, { fragments, operations }] of grouped) {
    // Generate fragments type
    const fragmentEntries = fragments
      .sort((a, b) => a.key.localeCompare(b.key))
      .map((f) => `    readonly "${f.key}": { readonly input: ${f.inputType}; readonly output: ${f.outputType} };`);

    // Generate operations type
    const operationEntries = operations
      .sort((a, b) => a.key.localeCompare(b.key))
      .map((o) => `    readonly "${o.key}": { readonly input: ${o.inputType}; readonly output: ${o.outputType} };`);

    lines.push(`export type PrebuiltTypes_${schemaName} = {`);
    lines.push("  readonly fragments: {");
    if (fragmentEntries.length > 0) {
      lines.push(...fragmentEntries);
    }
    lines.push("  };");
    lines.push("  readonly operations: {");
    if (operationEntries.length > 0) {
      lines.push(...operationEntries);
    }
    lines.push("  };");
    lines.push("} satisfies PrebuiltTypeRegistry;");
    lines.push("");
  }

  return lines.join("\n");
};

/**
 * Emit prebuilt types to the prebuilt/types.ts file.
 *
 * @param options - Emitter options including schemas, field selections, and output directory
 * @returns Result indicating success or failure
 */
export const emitPrebuiltTypes = async (
  options: PrebuiltTypesEmitterOptions,
): Promise<Result<{ path: string }, BuilderError>> => {
  const { schemas, fieldSelections, outdir } = options;

  // Group selections by schema
  const grouped = groupBySchema(fieldSelections, schemas);

  // Generate the types code
  const code = generateTypesCode(grouped);

  // Write to prebuilt/types.ts
  const typesPath = join(outdir, "prebuilt", "types.ts");

  try {
    await writeFile(typesPath, code, "utf-8");
    return ok({ path: typesPath });
  } catch (error) {
    return err(
      builderErrors.writeFailed(
        typesPath,
        `Failed to write prebuilt types: ${error instanceof Error ? error.message : String(error)}`,
        error,
      ),
    );
  }
};
