/**
 * type-names definitions
 * @generated by @soda-gql/tools/codegen
 */
export const typeNames_default = {
  scalar: ["ID", "String", "Int", "Float", "Boolean", "BigInt", "DateTime", "JSON"],
  enum: ["CacheScope", "EmployeeRole", "LogLevel", "ProjectStatus", "SortOrder", "TaskPriority"],
  input: ["BigIntFilter", "BooleanFilter", "CreateProjectInput", "CreateTaskInput", "DateTimeFilter", "DepartmentFilterInput", "EmployeeFilterInput", "EmployeeRoleFilter", "IntFilter", "PaginationInput", "ProjectFilterInput", "ProjectStatusFilter", "SortInput", "StringFilter", "TaskFilterInput", "TaskPriorityFilter", "TeamFilterInput", "TransferEmployeeInput", "UpdateProjectInput", "UpdateTaskInput"],
} as const;
export const typeNames_admin = {
  scalar: ["ID", "String", "Int", "Float", "Boolean", "BigInt", "DateTime", "JSON"],
  enum: ["EmployeeRole", "ProjectStatus", "TaskPriority"],
  input: [],
} as const;
