/**
 * type-names definitions
 * @generated by @soda-gql/tools/codegen
 */
export const typeNames_default = {
  scalar: ["BigInt", "Boolean", "DateTime", "Float", "ID", "Int", "JSON", "String"],
  enum: ["CacheScope", "EmployeeRole", "LogLevel", "ProjectStatus", "SortOrder", "TaskPriority"],
  input: ["BigIntFilter", "BooleanFilter", "CreateProjectInput", "CreateTaskInput", "DateTimeFilter", "DepartmentFilterInput", "EmployeeFilterInput", "EmployeeRoleFilter", "IntFilter", "PaginationInput", "ProjectFilterInput", "ProjectStatusFilter", "SortInput", "StringFilter", "TaskFilterInput", "TaskPriorityFilter", "TeamFilterInput", "TransferEmployeeInput", "UpdateProjectInput", "UpdateTaskInput"],
} as const;

export const typeNames_admin = {
  scalar: ["BigInt", "Boolean", "DateTime", "Float", "ID", "Int", "JSON", "String"],
  enum: ["EmployeeRole", "ProjectStatus", "TaskPriority"],
  input: [],
} as const;
