//! BuilderArtifact types ported from @soda-gql/builder.
//!
//! These types represent the pre-built metadata generated by the builder
//! service during static analysis.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Canonical identifier for a GQL definition.
/// Format: "filepath:scope.path"
pub type CanonicalId = String;

/// Metadata about the source of an artifact element.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuilderArtifactElementMetadata {
    pub source_path: String,
    pub source_hash: String,
    pub content_hash: String,
}

/// Prebuild data for a Model artifact.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelPrebuild {
    pub typename: String,
}

/// Prebuild data for a Slice artifact.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SlicePrebuild {
    pub operation_type: String,
}

/// Prebuild data for a composed Operation artifact.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OperationPrebuild {
    pub operation_type: String,
    pub operation_name: String,
    pub variable_names: Vec<String>,
    pub projection_path_graph: serde_json::Value,
    /// GraphQL document AST (complex object, not a string)
    pub document: serde_json::Value,
    #[serde(default)]
    pub metadata: Option<serde_json::Value>,
}

/// Prebuild data for an InlineOperation artifact.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineOperationPrebuild {
    pub operation_type: String,
    pub operation_name: String,
    pub variable_names: Vec<String>,
    /// GraphQL document AST (complex object, not a string)
    pub document: serde_json::Value,
    #[serde(default)]
    pub metadata: Option<serde_json::Value>,
}

/// A single artifact element from the builder.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum BuilderArtifactElement {
    #[serde(rename = "model")]
    Model {
        id: CanonicalId,
        metadata: BuilderArtifactElementMetadata,
        prebuild: ModelPrebuild,
    },
    #[serde(rename = "slice")]
    Slice {
        id: CanonicalId,
        metadata: BuilderArtifactElementMetadata,
        prebuild: SlicePrebuild,
    },
    #[serde(rename = "operation")]
    Operation {
        id: CanonicalId,
        metadata: BuilderArtifactElementMetadata,
        prebuild: OperationPrebuild,
    },
    #[serde(rename = "inlineOperation")]
    InlineOperation {
        id: CanonicalId,
        metadata: BuilderArtifactElementMetadata,
        prebuild: InlineOperationPrebuild,
    },
}

#[allow(dead_code)]
impl BuilderArtifactElement {
    /// Get the canonical ID of this element.
    pub fn id(&self) -> &str {
        match self {
            Self::Model { id, .. } => id,
            Self::Slice { id, .. } => id,
            Self::Operation { id, .. } => id,
            Self::InlineOperation { id, .. } => id,
        }
    }

    /// Get the element type as a string.
    pub fn element_type(&self) -> &'static str {
        match self {
            Self::Model { .. } => "model",
            Self::Slice { .. } => "slice",
            Self::Operation { .. } => "operation",
            Self::InlineOperation { .. } => "inlineOperation",
        }
    }
}

/// Build statistics from the builder service.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuilderArtifactStats {
    pub hits: usize,
    pub misses: usize,
    pub skips: usize,
}

/// Build report from the builder service.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuilderArtifactReport {
    pub duration_ms: u64,
    pub warnings: Vec<String>,
    pub stats: BuilderArtifactStats,
}

/// The complete artifact generated by the builder service.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuilderArtifact {
    pub elements: HashMap<CanonicalId, BuilderArtifactElement>,
    pub report: BuilderArtifactReport,
}

impl BuilderArtifact {
    /// Look up an element by its canonical ID.
    pub fn get(&self, id: &str) -> Option<&BuilderArtifactElement> {
        self.elements.get(id)
    }
}
