/**
 * TypeScript transformer for Nest CLI integration.
 *
 * This transformer integrates soda-gql's zero-runtime transformations
 * into the Nest CLI build process when using `builder: "tsc"`.
 */

import type * as ts from "typescript";
import {
  prepareTransform,
  typescriptTransformAdapterFactory,
  type TypeScriptAdapter,
} from "@soda-gql/plugin-shared";
import { waitForPromise } from "../core/wait-for-promise.js";

/**
 * Configuration for the soda-gql TypeScript transformer.
 */
export type TransformerConfig = {
  /**
   * Path to the artifact file generated by the builder.
   */
  readonly artifactPath: string;

  /**
   * Transform mode: "runtime" or "zero-runtime".
   * @default "runtime"
   */
  readonly mode?: "runtime" | "zero-runtime";

  /**
   * Import identifier for the GraphQL system.
   * @default "@/graphql-system"
   */
  readonly importIdentifier?: string;

  /**
   * Path to the soda-gql config file.
   */
  readonly configPath?: string;
};

/**
 * Create a TypeScript transformer for soda-gql.
 *
 * This factory signature matches the TypeScript compiler plugin API
 * expected by Nest CLI and other TypeScript tooling.
 *
 * @example
 * ```ts
 * // In tsconfig.json or nest-cli.json:
 * {
 *   "compilerOptions": {
 *     "plugins": [
 *       {
 *         "transform": "@soda-gql/plugin-nestjs/compiler/tsc",
 *         "artifactPath": "./dist/soda-gql-artifact.json",
 *         "mode": "zero-runtime"
 *       }
 *     ]
 *   }
 * }
 * ```
 */
export function createSodaGqlTransformer(
  program: ts.Program,
  rawConfig?: Partial<TransformerConfig>,
): ts.TransformerFactory<ts.SourceFile> {
  const config: TransformerConfig = {
    artifactPath: rawConfig?.artifactPath ?? "",
    mode: rawConfig?.mode ?? "runtime",
    importIdentifier: rawConfig?.importIdentifier ?? "@/graphql-system",
    configPath: rawConfig?.configPath,
  };

  // Validate required config
  if (!config.artifactPath) {
    throw new Error(
      "[@soda-gql/plugin-nestjs] artifactPath is required in transformer config",
    );
  }

  // Short-circuit for runtime mode - no transformation needed
  if (config.mode === "runtime") {
    return (context: ts.TransformationContext) => (sourceFile: ts.SourceFile) => sourceFile;
  }

  // Prepare transform state synchronously (blocks until ready)
  // This is cached per artifact path by prepareTransform
  const prepareResult = waitForPromise(
    prepareTransform({
      filename: program.getCompilerOptions().configFilePath?.toString() ?? "unknown",
      artifactPath: config.artifactPath,
      mode: config.mode as "runtime" | "zero-runtime",
      importIdentifier: config.importIdentifier,
      configPath: config.configPath,
    }),
  );

  // Handle preparation errors
  if (prepareResult.isErr()) {
    const error = prepareResult.error;
    console.error(
      "[@soda-gql/plugin-nestjs] Transform preparation failed:",
      error.message,
    );
    // Return no-op transformer
    return (context: ts.TransformationContext) => (sourceFile: ts.SourceFile) => sourceFile;
  }

  const { state } = prepareResult.value;

  return (context: ts.TransformationContext) => {
    return (sourceFile: ts.SourceFile) => {
      // Skip declaration files
      if (sourceFile.isDeclarationFile) {
        return sourceFile;
      }

      // Create TypeScript adapter
      const adapter = typescriptTransformAdapterFactory.create({
        sourceFile,
        context,
        typescript: require("typescript"),
      }) as TypeScriptAdapter;

      // Transform the program
      const transformContext = {
        filename: sourceFile.fileName,
        artifactLookup: (canonicalId: import("@soda-gql/builder").CanonicalId) =>
          state.allArtifacts[canonicalId],
      };

      const transformResult = adapter.transformProgram(transformContext);

      if (!transformResult.transformed) {
        return sourceFile;
      }

      // Insert runtime side effects
      adapter.insertRuntimeSideEffects(transformContext, transformResult.runtimeArtifacts ?? []);

      // The adapter updates sourceFile internally, retrieve it
      // This is a workaround until we refactor adapter to return transformed source
      return (adapter as unknown as { env: { sourceFile: ts.SourceFile } }).env.sourceFile;
    };
  };
}

/**
 * Default export for Nest CLI plugin resolution.
 */
export default createSodaGqlTransformer;
