/**
 * Prebuilt module generator for bundler-compatible type resolution.
 *
 * Generates a prebuilt version of the gql composer that uses
 * PrebuiltTypes for type lookup instead of complex inference.
 *
 * This generator minimizes imports from _internal.ts to enable
 * type serialization:
 * - Adapters (scalar, adapter) are imported from _internal-injects.ts
 * - Runtime values (__schema_*, etc.) are imported from _internal.ts
 * - Uses AnyGqlContext instead of heavy Context type inference
 *
 * @module
 */

import type { DocumentNode } from "graphql";

export type PrebuiltGeneratorOptions = {
  /**
   * Relative import path to the internal module.
   * Example: "../_internal" (from prebuilt/index.ts to _internal.ts)
   */
  readonly internalModulePath: string;
  /**
   * Relative import path to the injects module.
   * Example: "../_internal-injects" (from prebuilt/index.ts to _internal-injects.ts)
   */
  readonly injectsModulePath: string;
  /**
   * Per-schema injection config.
   * Maps schema name to whether it has an adapter.
   */
  readonly injection?: Map<
    string,
    {
      readonly hasAdapter?: boolean;
    }
  >;
};

export type PrebuiltGeneratedModule = {
  /** The generated code for index.prebuilt.ts */
  readonly indexCode: string;
};

/**
 * Generate the prebuilt module code.
 *
 * This generates:
 * - index.prebuilt.ts: Prebuilt composers using createPrebuiltGqlElementComposer
 * - types.prebuilt.ts: Placeholder types that typegen will populate
 *
 * The generated index.prebuilt.ts uses lightweight imports:
 * - Adapters from _internal-injects.ts (scalar, adapter)
 * - Runtime values from _internal.ts (__schema_*, __inputTypeMethods_*, __directiveMethods_*)
 * - Uses AnyGqlContext instead of heavy Context type inference
 */
export const generatePrebuiltModule = (
  schemas: Map<string, DocumentNode>,
  options: PrebuiltGeneratorOptions,
): PrebuiltGeneratedModule => {
  const schemaNames = Array.from(schemas.keys());
  const injection = options.injection ?? new Map();

  // Generate adapter imports from _internal-injects.ts
  const adapterImports: string[] = [];
  for (const name of schemaNames) {
    const config = injection.get(name);
    if (config?.hasAdapter) {
      adapterImports.push(`adapter_${name}`);
    }
  }

  // Generate internal imports (runtime values needed for composer creation)
  const internalImports = schemaNames.flatMap((name) => [
    `__schema_${name}`,
    `__inputTypeMethods_${name}`,
    `__directiveMethods_${name}`,
  ]);

  // Generate gql entries using createPrebuiltGqlElementComposer
  const gqlEntries = schemaNames.map((name) => {
    const config = injection.get(name);
    const adapterArg = config?.hasAdapter ? `adapter: adapter_${name},` : "";

    return `  ${name}: createPrebuiltGqlElementComposer<
    AnyGraphqlSchema,
    PrebuiltTypes_${name},
    Record<string, unknown>,
    StandardDirectives,
    AnyGqlContext
  >(
    __schema_${name} as AnyGraphqlSchema,
    {
      inputTypeMethods: __inputTypeMethods_${name},
      directiveMethods: __directiveMethods_${name},
      ${adapterArg}
    }
  )`;
  });

  // Build injects import line
  const injectsImportSpecifiers = adapterImports.length > 0 ? adapterImports.join(", ") : "";
  const injectsImportLine = injectsImportSpecifiers
    ? `import { ${injectsImportSpecifiers} } from "${options.injectsModulePath}";`
    : "";

  // Generate the prebuilt/index.ts code with lightweight imports
  const indexCode = `\
/**
 * Prebuilt GQL module for bundler-compatible type resolution.
 *
 * This module creates prebuilt composers using createPrebuiltGqlElementComposer
 * that look up types from PrebuiltTypes instead of complex inference.
 *
 * Uses lightweight imports:
 * - Adapters from _internal-injects.ts
 * - Runtime values from _internal.ts
 * - AnyGqlContext instead of heavy Context type inference
 *
 * @module
 * @generated by @soda-gql/typegen
 */

import {
  createPrebuiltGqlElementComposer,
  type AnyGqlContext,
  type AnyGraphqlSchema,
  type StandardDirectives,
} from "@soda-gql/core";
${injectsImportLine}
import { ${internalImports.join(", ")} } from "${options.internalModulePath}";
import type { ${schemaNames.map((name) => `PrebuiltTypes_${name}`).join(", ")} } from "./types.prebuilt";

/**
 * Prebuilt GQL composers with strict type resolution from PrebuiltTypeRegistry.
 *
 * These composers have the same runtime behavior as the base composers,
 * but their return types are resolved from the prebuilt type registry
 * instead of using complex type inference.
 */
export const gql = {
${gqlEntries.join(",\n")}
};
`;

  return {
    indexCode,
  };
};
