/**
 * Prebuilt module generator for bundler-compatible type resolution.
 *
 * Generates a prebuilt version of the gql composer that uses
 * PrebuiltTypes for type lookup instead of complex inference.
 *
 * This generator minimizes imports from _internal.ts to enable
 * type serialization. Only the `gql` object is imported at runtime,
 * and all types are inferred or imported from types.prebuilt.ts.
 *
 * @module
 */

import type { DocumentNode } from "graphql";

export type PrebuiltGeneratorOptions = {
  /**
   * Relative import path to the internal module.
   * Example: "./_internal" (from index.prebuilt.ts to _internal.ts)
   */
  readonly internalModulePath: string;
  /**
   * Per-schema injection config (adapter import paths).
   * Note: This is kept for API compatibility but no longer affects generation.
   */
  readonly injection?: Map<
    string,
    {
      readonly adapterImportPath?: string;
    }
  >;
};

export type PrebuiltGeneratedModule = {
  /** The generated code for index.prebuilt.ts */
  readonly indexCode: string;
  /** The generated code for types.prebuilt.ts (placeholder) */
  readonly typesCode: string;
};

/**
 * Generate the prebuilt module code.
 *
 * This generates:
 * - index.prebuilt.ts: Minimal wrapper that re-exports gql with prebuilt types
 * - types.prebuilt.ts: Placeholder types that typegen will populate
 *
 * The generated index.prebuilt.ts minimizes imports from _internal.ts:
 * - Only imports `gql` object (runtime dependency)
 * - Types are inferred from the base composer or imported from types.prebuilt.ts
 * - No individual schema/adapter/inputTypeMethods imports
 */
export const generatePrebuiltModule = (
  schemas: Map<string, DocumentNode>,
  options: PrebuiltGeneratorOptions,
): PrebuiltGeneratedModule => {
  const schemaNames = Array.from(schemas.keys());

  // Generate gql entries with type assertions
  // Context type is inferred from the base composer's function signature
  const gqlEntries = schemaNames.map(
    (name) =>
      `  ${name}: baseGql.${name} as unknown as PrebuiltGqlElementComposer<
    InferContext<typeof baseGql.${name}>,
    PrebuiltTypes_${name}
  > & { readonly $schema: typeof baseGql.${name}["$schema"] }`,
  );

  // Generate the prebuilt/index.ts code with minimal imports
  const indexCode = `\
/**
 * Prebuilt GQL module for bundler-compatible type resolution.
 *
 * This module wraps the base gql composers with PrebuiltGqlElementComposer
 * types that look up types from PrebuiltTypes instead of complex inference.
 *
 * Imports from _internal.ts are minimized to enable type serialization:
 * - Only the gql object is imported at runtime
 * - Context types are inferred from the base composer
 * - Prebuilt types are imported from types.prebuilt.ts
 *
 * @module
 * @generated by @soda-gql/typegen
 */

import type { PrebuiltGqlElementComposer } from "@soda-gql/core";
import { gql as baseGql } from "${options.internalModulePath}";
import type { ${schemaNames.map((name) => `PrebuiltTypes_${name}`).join(", ")} } from "./types.prebuilt";

/**
 * Infer the context type from a GQL element composer function.
 */
type InferContext<T> = T extends (fn: (ctx: infer C) => unknown) => unknown ? C : never;

/**
 * Prebuilt GQL composers with strict type resolution from PrebuiltTypeRegistry.
 *
 * These composers have the same runtime behavior as the base composers,
 * but their return types are resolved from the prebuilt type registry
 * instead of using complex type inference.
 */
export const gql = {
${gqlEntries.join(",\n")}
};
`;

  // Generate the prebuilt/types.ts placeholder
  const typesCode = `\
/**
 * Prebuilt type registry.
 *
 * This file contains placeholder types that will be populated by typegen
 * when running \`soda-gql typegen\` command.
 *
 * @module
 * @generated by @soda-gql/typegen
 */

import type { EmptyPrebuiltTypeRegistry } from "@soda-gql/core";

${schemaNames.map((name) => `// Placeholder for ${name} schema - populated by typegen\nexport type PrebuiltTypes_${name} = EmptyPrebuiltTypeRegistry;`).join("\n\n")}
`;

  return {
    indexCode,
    typesCode,
  };
};
