#!/usr/bin/env bun
import * as fs from "node:fs/promises";
import * as path from "node:path";

interface FixtureConfig {
  objectTypes: number;
  fragments: number;
  queries: number;
  operations: number;
}

const DEFAULT_CONFIG: FixtureConfig = {
  objectTypes: 10,
  fragments: 10,
  queries: 8,
  operations: 5,
};

// Backtick character for embedding tagged template syntax in generated code
const BT = "`";

function generateSchema(config: FixtureConfig): string {
  // Generate split object definitions using plain object literals with as const
  const objectDefinitions: string[] = [];

  // Query object definition - using direct object literal without function calls
  const queryFields: string[] = [];
  for (let i = 0; i < config.objectTypes; i++) {
    const typeName = `Entity${i}`;
    queryFields.push(`    ${typeName.toLowerCase()}: { kind: "object", name: "${typeName}", modifier: "?", arguments: {
      id: { kind: "scalar", name: "ID", modifier: "!", defaultValue: null, directives: {} },
    } },`);
    queryFields.push(`    ${typeName.toLowerCase()}List: { kind: "object", name: "${typeName}", modifier: "![]!", arguments: {
      limit: { kind: "scalar", name: "Int", modifier: "?", defaultValue: null, directives: {} },
      offset: { kind: "scalar", name: "Int", modifier: "?", defaultValue: null, directives: {} },
    } },`);
  }
  objectDefinitions.push(`const Query = {
  name: "Query",
  fields: {
${queryFields.join("\n")}
  },
} as const;`);

  // Mutation object definition
  const mutationFields: string[] = [];
  for (let i = 0; i < config.objectTypes; i++) {
    const typeName = `Entity${i}`;
    mutationFields.push(`    create${typeName}: { kind: "object", name: "${typeName}", modifier: "!", arguments: {
      name: { kind: "scalar", name: "String", modifier: "!", defaultValue: null, directives: {} },
      value: { kind: "scalar", name: "Int", modifier: "?", defaultValue: null, directives: {} },
    } },`);
    mutationFields.push(`    update${typeName}: { kind: "object", name: "${typeName}", modifier: "?", arguments: {
      id: { kind: "scalar", name: "ID", modifier: "!", defaultValue: null, directives: {} },
      name: { kind: "scalar", name: "String", modifier: "?", defaultValue: null, directives: {} },
    } },`);
    mutationFields.push(`    delete${typeName}: { kind: "scalar", name: "Boolean", modifier: "!", arguments: {
      id: { kind: "scalar", name: "ID", modifier: "!", defaultValue: null, directives: {} },
    } },`);
  }
  objectDefinitions.push(`const Mutation = {
  name: "Mutation",
  fields: {
${mutationFields.join("\n")}
  },
} as const;`);

  // Entity object definitions
  for (let i = 0; i < config.objectTypes; i++) {
    const typeName = `Entity${i}`;
    const relatedType = `Entity${(i + 1) % config.objectTypes}`;

    objectDefinitions.push(`const ${typeName} = {
  name: "${typeName}",
  fields: {
    id: { kind: "scalar", name: "ID", modifier: "!", arguments: {} },
    name: { kind: "scalar", name: "String", modifier: "!", arguments: {} },
    description: { kind: "scalar", name: "String", modifier: "?", arguments: {} },
    value: { kind: "scalar", name: "Int", modifier: "?", arguments: {} },
    score: { kind: "scalar", name: "Float", modifier: "?", arguments: {} },
    isActive: { kind: "scalar", name: "Boolean", modifier: "!", arguments: {} },
    createdAt: { kind: "scalar", name: "String", modifier: "!", arguments: {} },
    updatedAt: { kind: "scalar", name: "String", modifier: "?", arguments: {} },
    related: { kind: "object", name: "${relatedType}", modifier: "?", arguments: {} },
    relatedList: { kind: "object", name: "${relatedType}", modifier: "![]!", arguments: {
      limit: { kind: "scalar", name: "Int", modifier: "?", defaultValue: null, directives: {} },
    } },
  },
} as const;`);
  }

  // Object references for schema composition
  const objectRefs = ["Query", "Mutation"];
  for (let i = 0; i < config.objectTypes; i++) {
    objectRefs.push(`Entity${i}`);
  }
  const objectComposition = objectRefs.map((name) => `    ${name},`).join("\n");

  return `// Auto-generated schema for type-check benchmarking
// DO NOT EDIT - this file is generated by generate-fixtures.ts

import { createGqlElementComposer } from "@soda-gql/core";
import { defineAdapter, defineScalar } from "@soda-gql/core/adapter";

const scalars = {
  ...defineScalar<"ID", string, string>("ID"),
  ...defineScalar<"String", string, string>("String"),
  ...defineScalar<"Int", number, number>("Int"),
  ...defineScalar<"Float", number, number>("Float"),
  ...defineScalar<"Boolean", boolean, boolean>("Boolean"),
} as const;

const adapter = defineAdapter({
  helpers: {},
  metadata: {
    aggregateFragmentMetadata: (fragments) => fragments.map((m) => m.metadata),
  },
});

// Split object definitions with as const assertions
${objectDefinitions.join("\n\n")}

// Compose schema with as const
const schema = {
  label: "benchmark",
  operations: { query: "Query", mutation: "Mutation", subscription: null },
  scalar: scalars,
  enum: {},
  input: {},
  object: {
${objectComposition}
  },
  union: {},
} as const;

export const gql = {
  default: createGqlElementComposer(schema, { adapter }),
};

export { schema };
`;
}

function generateFragments(config: FixtureConfig): string {
  const fragments: string[] = [];

  for (let i = 0; i < config.fragments; i++) {
    const entityIndex = i % config.objectTypes;
    const typeName = `Entity${entityIndex}`;

    fragments.push(`
// Fragment ${i}: ${typeName} with nested selection
export const fragment${i} = gql.default(({ fragment }) =>
  fragment("${typeName}Fields${i}", "${typeName}")${BT}{
    id
    name
    description
    value
    isActive
    createdAt
    related {
      id
      name
      value
    }
    relatedList(limit: 5) {
      id
      name
    }
  }${BT}(),
);`);
  }

  return `// Auto-generated fragments for type-check benchmarking
// DO NOT EDIT - this file is generated by generate-fixtures.ts

import { gql } from "./schema";
${fragments.join("\n")}
`;
}

function generateQueries(config: FixtureConfig): string {
  const queries: string[] = [];

  for (let i = 0; i < config.queries; i++) {
    const entityIndex = i % config.objectTypes;
    const typeName = `Entity${entityIndex}`;

    // Alternate between single entity and list queries
    if (i % 2 === 0) {
      queries.push(`
// Query ${i}: Get single ${typeName} by ID
export const query${i} = gql.default(({ query }) =>
  query("Get${typeName}ById${i}")${BT}($id: ID!) {
    ${typeName.toLowerCase()}(id: $id) {
      id
      name
      description
      value
      isActive
    }
  }${BT}(),
);`);
    } else {
      queries.push(`
// Query ${i}: Get list of ${typeName}
export const query${i} = gql.default(({ query }) =>
  query("Get${typeName}List${i}")${BT}($limit: Int, $offset: Int) {
    ${typeName.toLowerCase()}List(limit: $limit, offset: $offset) {
      id
      name
      description
      value
      isActive
    }
  }${BT}(),
);`);
    }
  }

  return `// Auto-generated queries for type-check benchmarking
// DO NOT EDIT - this file is generated by generate-fixtures.ts

import { gql } from "./schema";
${queries.join("\n")}
`;
}

function generateOperations(config: FixtureConfig): string {
  const operations: string[] = [];

  for (let i = 0; i < config.operations; i++) {
    // Build operations that compose multiple fragments via tagged template interpolation
    const fragmentCount = Math.min(3, config.fragments);
    const fragmentImportIndices: Set<number> = new Set();
    const varDefs: string[] = [];
    const fieldSelections: string[] = [];

    for (let j = 0; j < fragmentCount; j++) {
      const fragIndex = (i * fragmentCount + j) % config.fragments;
      const entityIndex = fragIndex % config.objectTypes;
      const typeName = `Entity${entityIndex}`;
      const isListQuery = j % 2 !== 0;

      fragmentImportIndices.add(fragIndex);

      if (isListQuery) {
        varDefs.push(`$limit${j}: Int`);
        varDefs.push(`$offset${j}: Int`);
        fieldSelections.push(`    ${typeName.toLowerCase()}List(limit: $limit${j}, offset: $offset${j}) {
      ...\${fragment${fragIndex}}
    }`);
      } else {
        varDefs.push(`$id${j}: ID!`);
        fieldSelections.push(`    ${typeName.toLowerCase()}(id: $id${j}) {
      ...\${fragment${fragIndex}}
    }`);
      }
    }

    const varDefsStr = varDefs.length > 0 ? `(${varDefs.join(", ")}) ` : "";

    operations.push(`
// Operation ${i}: Composed operation with ${fragmentCount} fragment spreads
export const operation${i} = gql.default(({ query }) =>
  query("Operation${i}")${BT}${varDefsStr}{
${fieldSelections.join("\n")}
  }${BT}(),
);`);
  }

  // Collect all fragment imports needed
  const allFragmentIndices = new Set<number>();
  for (let i = 0; i < config.operations; i++) {
    const fragmentCount = Math.min(3, config.fragments);
    for (let j = 0; j < fragmentCount; j++) {
      const fragIndex = (i * fragmentCount + j) % config.fragments;
      allFragmentIndices.add(fragIndex);
    }
  }
  const fragmentImports = Array.from(allFragmentIndices).sort((a, b) => a - b).map((i) => `fragment${i}`).join(", ");

  return `// Auto-generated operations for type-check benchmarking
// DO NOT EDIT - this file is generated by generate-fixtures.ts

import { gql } from "./schema";
import { ${fragmentImports} } from "./fragments";
${operations.join("\n")}
`;
}

export async function generateFixtures(config: FixtureConfig = DEFAULT_CONFIG): Promise<void> {
  const generatedDir = path.join(import.meta.dirname, "..", "generated");

  await fs.mkdir(generatedDir, { recursive: true });

  const files = [
    { name: "schema.ts", content: generateSchema(config) },
    { name: "fragments.ts", content: generateFragments(config) },
    { name: "queries.ts", content: generateQueries(config) },
    { name: "operations.ts", content: generateOperations(config) },
  ];

  for (const file of files) {
    await fs.writeFile(path.join(generatedDir, file.name), file.content, "utf-8");
    console.log(`Generated: ${file.name}`);
  }

  console.log(`\nFixtures generated with config:`);
  console.log(`  Object types: ${config.objectTypes}`);
  console.log(`  Fragments: ${config.fragments}`);
  console.log(`  Queries: ${config.queries}`);
  console.log(`  Operations: ${config.operations}`);
}

// CLI entry point
if (import.meta.main) {
  const args = process.argv.slice(2);
  const config: FixtureConfig = { ...DEFAULT_CONFIG };

  for (let i = 0; i < args.length; i += 2) {
    const key = args[i]?.replace("--", "");
    const value = parseInt(args[i + 1] ?? "", 10);
    if (key && !isNaN(value) && key in config) {
      (config as unknown as Record<string, number>)[key] = value;
    }
  }

  generateFixtures(config).catch(console.error);
}
