/**
 * SWC transformer for Nest CLI integration.
 *
 * This transformer integrates soda-gql's zero-runtime transformations
 * into the Nest CLI build process when using `builder: "swc"`.
 */

import { type SwcAdapter, swcTransformAdapterFactory } from "@soda-gql/plugin-shared";
import type { Module } from "@swc/types";
import { prepareTransformSync } from "../core/prepare-transform-sync.js";

/**
 * Configuration for the soda-gql SWC transformer.
 */
export type TransformerConfig = {
  /**
   * Path to the artifact file generated by the builder.
   */
  readonly artifactPath: string;

  /**
   * Transform mode: "runtime" or "zero-runtime".
   * @default "runtime"
   */
  readonly mode?: "runtime" | "zero-runtime";

  /**
   * Import identifier for the GraphQL system.
   * @default "@/graphql-system"
   */
  readonly importIdentifier?: string;

  /**
   * Path to the soda-gql config file.
   */
  readonly configPath?: string;
};

/**
 * Create an SWC plugin for soda-gql.
 *
 * This plugin signature matches the SWC plugin API expected by Nest CLI.
 *
 * @example
 * ```json
 * // In nest-cli.json:
 * {
 *   "compilerOptions": {
 *     "builder": "swc",
 *     "swcPlugins": [
 *       [
 *         "@soda-gql/plugin-nestjs/compiler/swc",
 *         {
 *           "artifactPath": "./dist/soda-gql-artifact.json",
 *           "mode": "zero-runtime"
 *         }
 *       ]
 *     ]
 *   }
 * }
 * ```
 */
export function createSodaGqlSwcPlugin(rawConfig?: Partial<TransformerConfig>) {
  const config: TransformerConfig = {
    artifactPath: rawConfig?.artifactPath ?? "",
    mode: rawConfig?.mode ?? "runtime",
    importIdentifier: rawConfig?.importIdentifier ?? "@/graphql-system",
    configPath: rawConfig?.configPath,
  };

  // Validate required config
  if (!config.artifactPath) {
    throw new Error("[@soda-gql/plugin-nestjs] artifactPath is required in transformer config");
  }

  // Short-circuit for runtime mode - no transformation needed
  if (config.mode === "runtime") {
    return (m: Module) => m;
  }

  // Prepare transform state synchronously
  // This reads the artifact from disk and caches it
  const prepareResult = prepareTransformSync({
    artifactPath: config.artifactPath,
    importIdentifier: config.importIdentifier,
  });

  // Handle preparation errors
  if (prepareResult.isErr()) {
    const error = prepareResult.error;
    console.error(
      `[@soda-gql/plugin-nestjs] Transform preparation failed (${error.type}):`,
      error.type === "ARTIFACT_NOT_FOUND" ? `Artifact not found at ${error.path}` : error.type,
    );
    // Return no-op transformer
    return (m: Module) => m;
  }

  const prepared = prepareResult.value;

  return (m: Module, options: { filename: string; swc: typeof import("@swc/core") }): Module => {
    const filename = options.filename;

    // Create SWC adapter
    const adapter = swcTransformAdapterFactory.create({
      module: m,
      swc: options.swc,
      filename,
    }) as SwcAdapter;

    // Transform the program
    const transformContext = {
      filename,
      artifactLookup: (canonicalId: import("@soda-gql/builder").CanonicalId) => prepared.allArtifacts[canonicalId],
    };

    const transformResult = adapter.transformProgram(transformContext);

    if (!transformResult.transformed) {
      return m;
    }

    // Insert runtime side effects
    adapter.insertRuntimeSideEffects(transformContext, transformResult.runtimeArtifacts ?? []);

    // The adapter updates module internally, retrieve it
    // This is a workaround until we refactor adapter to return transformed module
    return (adapter as unknown as { env: { module: Module } }).env.module;
  };
}

/**
 * Default export for Nest CLI plugin resolution.
 *
 * Nest CLI expects a function that returns the plugin function.
 */
export default function sodaGqlSwcPlugin(config?: Partial<TransformerConfig>) {
  return createSodaGqlSwcPlugin(config);
}
