/**
 * Type definitions for prebuilt type system.
 *
 * These types enable looking up pre-computed types from a registry
 * instead of relying on complex type inference that may be lost
 * when bundling with tools like tsdown.
 *
 * @module
 */

/**
 * Registry mapping fragment/operation keys to their inferred types.
 * Generated by the builder and used by prebuilt composers.
 */
export type PrebuiltTypeRegistry = {
  readonly fragments: {
    readonly [key: string]: {
      readonly input: unknown;
      readonly output: object;
    };
  };
  readonly operations: {
    readonly [key: string]: {
      readonly input: object;
      readonly output: object;
    };
  };
};

/**
 * Empty registry type for when no prebuilt types are available.
 */
export type EmptyPrebuiltTypeRegistry = {
  readonly fragments: Record<string, never>;
  readonly operations: Record<string, never>;
};

/**
 * Extract the input type for a fragment from the registry.
 */
export type PrebuiltFragmentInput<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends keyof TRegistry["fragments"] & string,
> = TRegistry["fragments"][TKey]["input"];

/**
 * Extract the output type for a fragment from the registry.
 */
export type PrebuiltFragmentOutput<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends keyof TRegistry["fragments"] & string,
> = TRegistry["fragments"][TKey]["output"];

/**
 * Extract the input type for an operation from the registry.
 */
export type PrebuiltOperationInput<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends keyof TRegistry["operations"] & string,
> = TRegistry["operations"][TKey]["input"];

/**
 * Extract the output type for an operation from the registry.
 */
export type PrebuiltOperationOutput<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends keyof TRegistry["operations"] & string,
> = TRegistry["operations"][TKey]["output"];

/**
 * Check if a key exists in the fragment registry.
 */
export type HasPrebuiltFragment<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends string,
> = TKey extends keyof TRegistry["fragments"] ? true : false;

/**
 * Check if a key exists in the operation registry.
 */
export type HasPrebuiltOperation<
  TRegistry extends PrebuiltTypeRegistry,
  TKey extends string,
> = TKey extends keyof TRegistry["operations"] ? true : false;
