/**
 * Type definitions for prebuilt type system.
 *
 * These types enable looking up pre-computed types from a registry
 * instead of relying on complex type inference that may be lost
 * when bundling with tools like tsdown.
 *
 * @module
 */

/**
 * Registry mapping fragment/operation keys to their inferred types.
 * Generated by the builder and used by prebuilt composers.
 */
export type PrebuiltTypeRegistry = {
  readonly fragments: {
    readonly [key: string]: {
      readonly input: unknown;
      readonly output: object;
    };
  };
  readonly operations: {
    readonly [key: string]: {
      readonly input: object;
      readonly output: object;
    };
  };
};

/**
 * Branded error type for missing prebuilt registry entries.
 *
 * This type intentionally produces a clear error message at compile time
 * when an operation or fragment is not found in the PrebuiltTypeRegistry.
 * Instead of silently falling back to inferred types, this forces users
 * to ensure all elements are properly registered via typegen.
 */
export type PrebuiltEntryNotFound<TKey extends string, TKind extends "fragment" | "operation"> = {
  readonly __error: "PREBUILT_ENTRY_NOT_FOUND";
  readonly __message: `${TKind} "${TKey}" not found in PrebuiltTypeRegistry. Run 'soda-gql typegen' to generate prebuilt types.`;
  readonly __key: TKey;
  readonly __kind: TKind;
};
