/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Transform a single source file.
 *
 * # Arguments
 * * `input_json` - JSON-serialized TransformInput containing source code, file path, artifact, and config
 *
 * # Returns
 * JSON-serialized TransformResult containing the transformed code
 */
export declare function transform(inputJson: string): string
/**
 * Stateful transformer that caches artifact and config for multiple file transformations.
 *
 * The artifact is parsed once in the constructor and reused for all subsequent
 * transform calls, avoiding repeated JSON parsing overhead.
 */
export declare class SwcTransformer {
  /**
   * Create a new transformer instance.
   *
   * # Arguments
   * * `artifact_json` - JSON-serialized BuilderArtifact
   * * `config_json` - JSON-serialized TransformConfig
   */
  constructor(artifactJson: string, configJson: string)
  /**
   * Transform a single source file.
   *
   * # Arguments
   * * `source_code` - The source code to transform
   * * `source_path` - The file path of the source
   *
   * # Returns
   * JSON-serialized TransformResult
   */
  transform(sourceCode: string, sourcePath: string): string
}
