/**
 * Generated by @soda-gql/tools/codegen
 * @module
 * @generated
 */

export * from "./_internal";
import { __gql_default } from "./_internal";
import type { Schema_default } from "./_internal";
import type { __directiveMethods_default } from "./_internal";
import type { PrebuiltTypes_default } from "./types.prebuilt";
import type { Fragment, AnyFragment, Operation, OperationType, PrebuiltEntryNotFound, AnyConstAssignableInput, AnyFields, AnyGraphqlSchema, AnyOperation, GqlDefine } from "@soda-gql/core";

type ResolveFragmentAtBuilder_default<TKey extends string> =
  TKey extends keyof PrebuiltTypes_default["fragments"]
    ? Fragment<
        PrebuiltTypes_default["fragments"][TKey]["typename"],
        PrebuiltTypes_default["fragments"][TKey]["input"] extends void
          ? void
          : Partial<PrebuiltTypes_default["fragments"][TKey]["input"] & AnyConstAssignableInput>,
        Partial<AnyFields>,
        PrebuiltTypes_default["fragments"][TKey]["output"] & object
      >
    : Fragment<"(unknown)", PrebuiltEntryNotFound<TKey, "fragment">, Partial<AnyFields>, PrebuiltEntryNotFound<TKey, "fragment">>;

type ResolveOperationAtBuilder_default<TOperationType extends OperationType, TName extends string> =
  TName extends keyof PrebuiltTypes_default["operations"]
    ? Operation<
        TOperationType,
        TName,
        string[],
        PrebuiltTypes_default["operations"][TName]["input"],
        Partial<AnyFields>,
        PrebuiltTypes_default["operations"][TName]["output"] & object
      >
    : Operation<
        TOperationType,
        TName,
        string[],
        PrebuiltEntryNotFound<TName, "operation">,
        Partial<AnyFields>,
        PrebuiltEntryNotFound<TName, "operation">
      >;

type PrebuiltCurriedFragment_default = <TKey extends string>(
  name: TKey,
  typeName: string,
) => ((options: { fields: (tools: GenericFieldsBuilderTools_default) => Record<string, unknown> }) => (...args: unknown[]) => ResolveFragmentAtBuilder_default<TKey>)
  & ((strings: TemplateStringsArray, ...values: (AnyFragment | ((ctx: { $: Readonly<Record<string, unknown>> }) => Record<string, unknown>))[]) => (...args: unknown[]) => ResolveFragmentAtBuilder_default<TKey>);

type PrebuiltCurriedOperation_default<TOperationType extends OperationType> = <TName extends string>(
  operationName: TName,
) => ((options: { variables?: string; fields: (tools: GenericFieldsBuilderTools_default) => Record<string, unknown> }) => (...args: unknown[]) => ResolveOperationAtBuilder_default<TOperationType, TName>)
  & ((strings: TemplateStringsArray, ...values: (AnyFragment | ((ctx: { $: Readonly<Record<string, unknown>> }) => Record<string, unknown>))[]) => (...args: unknown[]) => ResolveOperationAtBuilder_default<TOperationType, TName>);

// biome-ignore lint/suspicious/noExplicitAny: Type-erased field accessor — returns callable result for nested builders
type GenericFieldAccessor_default = (fieldName: string, ...args: any[]) => {
  (callback: (tools: { f: GenericFieldAccessor_default }) => Record<string, unknown>): Record<string, unknown>;
  (...args: any[]): Record<string, unknown>;
};
type GenericFieldsBuilderTools_default = { readonly f: GenericFieldAccessor_default; readonly $: Readonly<Record<string, never>> };

export type PrebuiltContext_default = {
  readonly fragment: PrebuiltCurriedFragment_default;
  readonly query: PrebuiltCurriedOperation_default<"query"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly mutation: PrebuiltCurriedOperation_default<"mutation"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly subscription: PrebuiltCurriedOperation_default<"subscription"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly define: <TValue>(factory: () => TValue | Promise<TValue>) => GqlDefine<TValue>;
  readonly extend: (...args: unknown[]) => AnyOperation;
  readonly $dir: typeof __directiveMethods_default;
  readonly $colocate: <T extends Record<string, unknown>>(projections: T) => T;
};

type GqlComposer_default = {
  <TResult>(composeElement: (context: PrebuiltContext_default) => TResult): TResult;
  readonly $schema: AnyGraphqlSchema;
};

export const gql = {
  default: __gql_default as unknown as GqlComposer_default
};
