/**
 * Generated by @soda-gql/tools/codegen
 * @module
 * @generated
 */

export * from "./_internal";
import { __gql_default } from "./_internal";
import type { Schema_default } from "./_internal";
import type { __directiveMethods_default } from "./_internal";
import type { Context_default } from "./_internal";
import type { PrebuiltTypes_default } from "./types.prebuilt";
import type { Fragment, AnyFragment, Operation, OperationType, PrebuiltEntryNotFound, AnyConstAssignableInput, AnyFields, AnyGraphqlSchema, AnyOperation, GqlDefine, MetadataBuilder, OperationMetadata, OperationDocumentTransformer, VarRefsFromVarTypes } from "@soda-gql/core";

type ResolveFragmentAtBuilder_default<TKey extends string> =
  TKey extends keyof PrebuiltTypes_default["fragments"]
    ? Fragment<
        PrebuiltTypes_default["fragments"][TKey]["typename"],
        PrebuiltTypes_default["fragments"][TKey]["input"] extends void
          ? void
          : Partial<PrebuiltTypes_default["fragments"][TKey]["input"] & AnyConstAssignableInput>,
        Partial<AnyFields>,
        PrebuiltTypes_default["fragments"][TKey]["output"] & object
      >
    : Fragment<"(unknown)", PrebuiltEntryNotFound<TKey, "fragment">, Partial<AnyFields>, PrebuiltEntryNotFound<TKey, "fragment">>;

type ResolveOperationAtBuilder_default<TOperationType extends OperationType, TName extends string> =
  TName extends keyof PrebuiltTypes_default["operations"]
    ? Operation<
        TOperationType,
        TName,
        string[],
        PrebuiltTypes_default["operations"][TName]["input"],
        Partial<AnyFields>,
        PrebuiltTypes_default["operations"][TName]["output"] & object
      >
    : Operation<
        TOperationType,
        TName,
        string[],
        PrebuiltEntryNotFound<TName, "operation">,
        Partial<AnyFields>,
        PrebuiltEntryNotFound<TName, "operation">
      >;

type PrebuiltCurriedFragment_default = <TKey extends string>(
  name: TKey,
  typeName: string,
) => ((options: { fields: (tools: GenericFieldsBuilderTools_default) => Record<string, unknown> }) => (...args: unknown[]) => ResolveFragmentAtBuilder_default<TKey>)
  & ((strings: TemplateStringsArray, ...values: (AnyFragment | ((ctx: { $: Readonly<Record<string, unknown>> }) => Record<string, unknown>))[]) => (...args: unknown[]) => ResolveFragmentAtBuilder_default<TKey>);

// Per-operation variable payload types, backing the metadata builder's typed `$`/`$var` tools.
type ResolveVarTypes_default<TName extends string> =
  TName extends keyof PrebuiltTypes_default["operations"]
    ? PrebuiltTypes_default["operations"][TName]["varTypes"]
    : Record<string, never>;

// Trailing operation-builder options; `TMetadata` is inferred from a static value or the
// builder callback's return, whose `$` is typed from the operation's variables.
type PrebuiltOperationOptions_default<TName extends string, TMetadata> = {
  readonly metadata?: TMetadata | MetadataBuilder<VarRefsFromVarTypes<ResolveVarTypes_default<TName>>, TMetadata>;
  readonly transformDocument?: OperationDocumentTransformer<TMetadata>;
};

type PrebuiltCurriedOperation_default<TOperationType extends OperationType> = <TName extends string>(
  operationName: TName,
) => ((options: { variables?: string; fields: (tools: GenericFieldsBuilderTools_default) => Record<string, unknown> }) => <TMetadata = OperationMetadata>(options?: PrebuiltOperationOptions_default<TName, TMetadata>) => ResolveOperationAtBuilder_default<TOperationType, TName>)
  & ((strings: TemplateStringsArray, ...values: (AnyFragment | ((ctx: { $: Readonly<Record<string, unknown>> }) => Record<string, unknown>))[]) => <TMetadata = OperationMetadata>(options?: PrebuiltOperationOptions_default<TName, TMetadata>) => ResolveOperationAtBuilder_default<TOperationType, TName>);

// biome-ignore lint/suspicious/noExplicitAny: Type-erased field accessor — returns callable result for nested builders
type GenericFieldAccessor_default = (fieldName: string, ...args: any[]) => {
  (callback: (tools: { f: GenericFieldAccessor_default }) => Record<string, unknown>): Record<string, unknown>;
  (...args: any[]): Record<string, unknown>;
};
type GenericFieldsBuilderTools_default = { readonly f: GenericFieldAccessor_default; readonly $: Readonly<Record<string, never>> };

// Adapter helpers are whatever the composer context carries beyond the core members
// replaced by the prebuilt-backed versions below (empty when no adapter is configured).
type AdapterHelpers_default = Omit<Context_default, "fragment" | "query" | "mutation" | "subscription" | "define" | "extend" | "$dir" | "$colocate">;

export type PrebuiltContext_default = AdapterHelpers_default & {
  readonly fragment: PrebuiltCurriedFragment_default;
  readonly query: PrebuiltCurriedOperation_default<"query"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly mutation: PrebuiltCurriedOperation_default<"mutation"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly subscription: PrebuiltCurriedOperation_default<"subscription"> & {
    readonly compat: (operationName: string) => (strings: TemplateStringsArray, ...values: never[]) => GqlDefine<unknown>;
  };
  readonly define: <TValue>(factory: () => TValue | Promise<TValue>) => GqlDefine<TValue>;
  readonly extend: (...args: unknown[]) => AnyOperation;
  readonly $dir: typeof __directiveMethods_default;
  readonly $colocate: <T extends Record<string, unknown>>(projections: T) => T;
};

type GqlComposer_default = {
  <TResult>(composeElement: (context: PrebuiltContext_default) => TResult): TResult;
  readonly $schema: AnyGraphqlSchema;
};

export const gql = {
  default: __gql_default as unknown as GqlComposer_default
};
